-- This file is generated by gen.go. Do not edit.
-- Run `go run gen.go` to regenerate.

function expand(str)
	if str == "aa" then
		return "append(,)", -2
	end
	if str == "ife" then
		return "if err != nil {\n\t\n\t}\n", -4
	end
	if str == "ie" then
		return "if err := ", 0
	end
	if str == ";e" then
		return "err != nil {\t\n\t\t\n\t}", -3
	end
	if str == "re" then
		return "return err", 0
	end
	if str == "rn" then
		return "return nil", 0
	end
	if str == "ew" then
		return "errors.Wrap(err, \"\")", -2
	end
	if str == "pp" then
		return "println(\"=== \")", -2
	end
	if str == "pps" then
		return "println(\"=== \", fmt.Sprintf(\"%\",))", -4
	end
	if str == "fu" then
		return "func () {\n}\n", -7
	end
	if str == "tt" then
		return "func Test(t*testing.T)", -1
	end
	if str == "tl" then
		return "t.Log(\"\",)", -2
	end
	if str == "tlf" then
		return "t.Logf(\"\",)", -3
	end
	if str == "tf" then
		return "t.Fatal(err)", 0
	end
	if str == "ff" then
		return "fmt.Printf(\"\",)", -3
	end
	if str == "fff" then
		return "fmt.Fprintf(w, \"\",)", -3
	end
	if str == "sp" then
		return "fmt.Sprintf(\"\",)", -3
	end
	if str == "fe" then
		return "fmt.Errorf(\"\",)", -3
	end
	if str == "fp" then
		return "fmt.Println()", -1
	end
	if str == "lp" then
		return "log.Println()", -1
	end
	if str == "lpf" then
		return "log.Printf(\"\",)", -3
	end
	if str == "lf" then
		return "log.Fatal(err)", -1
	end
	if str == "ss." then
		return "strings.", 0
	end
	if str == "ra" then
		return "ioutil.ReadAll()", -1
	end
	if str == "wa" then
		return "ioutil.WriteAll()", -1
	end
	if str == "rf" then
		return "ioutil.ReadFile(fname)", -1
	end
	if str == "wf" then
		return "ioutil.WriteFile(fname,,0600)", -6
	end
	if str == "he" then
		return "http.Error(w, err.Error(), http.StatusInternalServerError)\nreturn\n", 0
	end
	if str == "hw" then
		return "w http.ResponseWriter", 0
	end
	if str == "hr" then
		return "r*http.ResponseReader", 0
	end
	return "", 0
end
